'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
require('../assets/bazi-core.js');
require('../assets/market-trend-core.js');
const Y=require('../assets/bazi-annual-core.js');
const doc=JSON.parse(fs.readFileSync('data/market-history.json','utf8'));
const gold=doc.data.XAUUSD,silver=doc.data.XAGUSD;
assert.ok(gold.length>=800&&silver.length>=800);
for(const series of [gold,silver]){
 const p=Y.analyze(series,2026);
 assert.equal(p.year,2026);
 assert.equal(p.element,'Api');
 assert.equal(p.animal,'Kuda');
 assert.equal(p.matching.n,1,'1966 is the only complete Fire Horse analogue');
 assert.equal(p.byElement.n,12);
 assert.equal(p.byShio.n,5);
 assert.equal(p.samples,66);
 assert.equal(p.cutoff,2025);
 assert.equal(p.dominant,'TIDAK KONKLUSIF','No unsupported annual buy/sell signal');
 assert.equal(p.full,null,'Incomplete 2026 may not be called a full-year return');
 assert.equal(p.partial.to,'2026-09');
 assert.ok(Number.isFinite(p.partial.change));
 assert.equal(Y.annual(series,1966).change,0);
 assert.equal(Y.annual(series,2026),null);
 assert.equal(Y.analyze(series,2027).samples,66,'Incomplete 2026 must not enter 2027 cohort');
 assert.equal(Y.analyze(series,2027).cutoff,2025);
 assert.throws(()=>Y.analyze(series,2051),/tahun/);
}
const r=Y.analyze(gold,2026);
assert.equal(r.byElement.up,9);
assert.equal(r.byShio.up,2);
const s=Y.analyze(silver,2026);
assert.equal(s.byElement.up,8);
assert.equal(s.byShio.up,2);
assert.equal(Y.sample([],4).bias,'TIDAK CUKUP DATA');
assert.equal(Y.sample([{change:1},{change:2},{change:3},{change:-1}],4).bias,'BULLISH');
assert.equal(Y.sample([{change:-1},{change:-2},{change:-3},{change:1}],4).bias,'BEARISH');
const short=gold.filter(r=>r[0]!=='1986-08');
assert.equal(Y.annual(short,1986),null,'A price gap must invalidate a full 12-month cycle');
const index=fs.readFileSync('index.html','utf8');
for(const path of ['assets/bazi-annual-core.js','assets/bazi-annual-ui.js'])assert.ok(index.includes(path));
const annualUI=fs.readFileSync('assets/bazi-annual-ui.js','utf8');
assert.ok(!/[\u3400-\u9fff]/u.test(annualUI),'No Chinese characters in displayed UI');
assert.ok(annualUI.includes('XAUUSD')&&annualUI.includes('XAGUSD'));
assert.ok(annualUI.includes('2026')&&annualUI.includes('2036'));
assert.ok(fs.readFileSync('assets/market-trend-ui.js','utf8').includes('cebonk:market-history'));
console.log('PASS: annual BaZi-year proxies 1960–2025, 2026 partial, cohort counts, no leakage, insufficient-sample guard and Indonesian UI.');
