/* BaZi regression: run with lunar-javascript@1.7.7 available through NODE_PATH. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {Solar}=require('lunar-javascript');
const B=require('../assets/bazi-core.js');
const src=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('assets/bazi-ui.js','utf8');
assert.equal(B.VERSION,'1.0.0');
assert.equal(B.yearCycle(1906).text,'丙午');
assert.equal(B.yearCycle(1966).text,'丙午');
assert.equal(B.yearCycle(2026).text,'丙午');
assert.equal(B.yearCycle(2026).element,'Api');
assert.equal(B.yearCycle(2050).text,'庚午');
assert.equal(B.yearCycle(1984).text,'甲子');
assert.equal(B.years(1912,2055).length,144);
const normal=B.calculate(Solar,'2005-12-23','08:37');
assert.deepEqual(['year','month','day','hour'].map(k=>normal.pillars[k].text),['乙酉','戊子','辛巳','壬辰']);
assert.equal(Object.values(normal.elements).reduce((n,v)=>n+v,0),8);
const pre=B.calculate(Solar,'2026-02-01','12:00');
const post=B.calculate(Solar,'2026-10-09','12:00');
assert.equal(pre.pillars.year.text,'乙巳','Li Chun: before is still Snake');
assert.equal(post.pillars.year.text,'丙午','Li Chun: after is Fire Horse');
const late2=B.calculate(Solar,'1988-02-15','23:30',2);
const late1=B.calculate(Solar,'1988-02-15','23:30',1);
assert.equal(late2.pillars.day.text,'庚子');
assert.equal(late1.pillars.day.text,'辛丑');
assert.equal(late2.pillars.hour.zhi,'子');
const slots=B.periods(Solar,'2026-10-09');
assert.equal(slots.length,13);
assert.equal(slots[0].range,'00:00–00:59');
assert.equal(slots[12].range,'23:00–23:59');
assert.equal(slots[11].range,'21:00–22:59');
assert.equal(slots[12].pillars.hour.zhi,'子');
assert.equal(slots[1].pillars.hour.zhi,'丑');
assert.equal(B.wibToUTC('2026-10-09','07:00'),Date.UTC(2026,9,9,0,0));
assert.deepEqual(B.solarParts(B.wibToUTC('2026-10-09','23:30'),8),[2026,10,10,0,30]);
assert.throws(()=>B.parse('2026-02-30','12:00'),/tidak valid/);
assert.throws(()=>B.parse('2026-10-09','24:00'),/00:00/);
assert.equal(B.todayWIB(Date.UTC(2026,9,9,0,0)).time,'07:00');
assert(src.includes('assets/bazi-core.js?v=1.0.0'));
assert(src.includes('assets/bazi-ui.js?v=1.3.0'));
assert(src.indexOf('assets/bazi-core.js')<src.indexOf('assets/bazi-ui.js'));
for(const legacy of ['assets/astro-news-v1.js','assets/astro-candles.js','assets/astro-daily-brief.js'])assert(src.includes(legacy));
for(const removed of ['tabBBMA','tabLiquidity','assets/technical-scanners-core.js','assets/technical-scanners-ui.js'])assert(!src.includes(removed));
assert(ui.includes("tab.id='tabBazi'"));
assert(ui.includes('astroNewsView'));
assert(ui.includes('TIDAK_DIHITUNG'),'No market direction output');
console.log('PASS: Four Pillars, Li Chun, Sect 1/2, WIB→Beijing, 13 periods, 60-year Horse, legacy preservation.');
