'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
require('../assets/bazi-core.js');require('../assets/market-trend-core.js');
const F=require('../assets/fundamental-60y-core.js');
const archive=JSON.parse(fs.readFileSync('data/market-history.json','utf8'));
assert.equal(archive.frequency,'monthly_average');
assert.ok(F.validateEvents(F.EVENTS));
assert.ok(F.EVENTS.length>=10);
for(const e of F.EVENTS){
 assert.ok(e.sources.length);
 assert.ok(e.sources.every(x=>x.url.startsWith('https://')));
 assert.ok(e.metals.length);
}
for(const symbol of ['XAUUSD','XAGUSD']){
 const prices=archive.data[symbol];
 const result=F.compare(prices,2026,symbol);
 assert.deepEqual(result.cycle,{animal:'Kuda',element:'Api'});
 assert.equal(result.olderYear,1966);
 assert.equal(result.previous.year,1966);
 assert.equal(result.previous.complete,true);
 assert.equal(result.selected.year,2026);
 assert.equal(result.selected.complete,false);
 assert.equal(result.selected.label,'BELUM LENGKAP');
 assert.equal(result.selected.comparison,'BULAN SEPADAN (SEMENTARA)');
 assert.equal(result.selected.months,9);
 assert.ok(result.events.length>=1);
 assert.ok(result.previousEvents.length>=1);
 assert.ok(result.events.every(e=>e.metals.includes(symbol)));
 assert.ok(result.previousEvents.every(e=>e.metals.includes(symbol)));
 assert.ok(result.warnings.some(x=>x.includes('tidak membuktikan sebab')));
 assert.ok(!Object.hasOwn(result.selected,'open'));
 assert.ok(!Object.hasOwn(result.selected,'high'));
 assert.ok(!Object.hasOwn(result.selected,'low'));
 assert.ok(!Object.hasOwn(result.selected,'close'));
 assert.equal(F.compare(prices,1966,symbol).olderYear,null);
}
assert.equal(F.eventsForYear(1967,'XAGUSD',0).some(e=>e.date==='1967-07-01'),true);
assert.equal(F.eventsForYear(1980,'XAGUSD',0).some(e=>e.title.includes('Hunt')),true);
assert.equal(F.eventsForYear(1971,'XAUUSD',0).some(e=>e.date==='1971-08-15'),true);
assert.equal(F.eventsForYear(1971,'XAGUSD',0).some(e=>e.date==='1971-08-15'),false);
const gold=archive.data.XAUUSD;
assert.equal(F.priceYear(gold,1950),null);
const full=F.priceYear(gold,2025);
assert.equal(full.complete,true);
assert.equal(full.comparison,'TAHUN PENUH');
assert.equal(F.priceYear(gold.filter(v=>v[0]!=='2025-06'),2025).label,'BELUM LENGKAP');
assert.throws(()=>F.eventsForYear(2026,'BTCUSD'),/Instrumen/);
assert.throws(()=>F.compare(gold,2051,'XAUUSD'),/1960/);
assert.throws(()=>F.validateEvents([{date:'2026-02-30',end:'2026-03-01',metals:['XAUUSD']}]),/Rentang/);
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('assets/fundamental-60y-ui.js','utf8');
const shortcuts=fs.readFileSync('assets/bazi-ui.js','utf8');
assert.ok(html.includes('assets/fundamental-60y-core.js?v=1.0.0'));
assert.ok(html.includes('assets/fundamental-60y-ui.js?v=1.0.0'));
assert.ok(html.indexOf('fundamental-60y-core.js')<html.indexOf('fundamental-60y-ui.js'));
assert.ok(shortcuts.includes('data-bz-target="f60Panel"'));
assert.ok(shortcuts.includes("'mhPanel','f60Panel'"));
assert.ok(!/[\u3400-\u9fff]/u.test(ui),'All labels should be Indonesian, without Hanzi');
assert.ok(ui.includes('Tidak')||ui.includes('tidak'));
assert.ok(ui.includes('cebonk:market-history'));
assert.ok(!html.includes('technical-scanners-core.js'));
console.log('PASS: fundamental 60-year BaZi compares gold/silver data, validates source chronology, labels partial years, separates observational vs causal claims, and integrates visible Indonesian UI.');
