'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const H=require('../assets/market-trend-core.js');
const months=Array.from({length:25},(_,i)=>[String(2023+Math.floor(i/12))+'-'+String(i%12+1).padStart(2,'0'),100+i*2]);
assert.equal(H.rows(months).length,25);
const t=H.trend(months);
assert.equal(t.ok,true);
assert.equal(t.direction,'NAIK');
assert.equal(t.month,'2025-01');
assert.ok(t.change[12]>0);
assert.ok(t.change[3]>0);
assert.equal(t.price,148);
assert.equal(H.trend(months.slice(0,4)).ok,false);
assert.equal(H.trend(months.filter(x=>x[0]!=='2024-08')).ok,false);
assert.throws(()=>H.rows([['2024-01',100],['2024-01',101]]),/Duplikasi/);
assert.throws(()=>H.rows([['2024-13',100]]),/Format/);
const year=Array.from({length:12},(_,i)=>['1966-'+String(i+1).padStart(2,'0'),100+i]);
assert.equal(H.horseYear(year,1966).complete,true);
assert.equal(H.horseYear(year.slice(1),1966).complete,false);
const imported=H.csv('date,close\n'+Array.from({length:25},(_,i)=>`2023-${String(i%12+1).padStart(2,'0')}-01,${100+i}`).join('\n'));
assert.equal(imported.data.length,12);
assert.equal(imported.method,'Rata-rata penutupan harian CSV');
const daily=H.csv('date,close\n'+Array.from({length:26},(_,i)=>`2025-01-${String(i+1).padStart(2,'0')},${10+i}`).join('\n'));
assert.equal(daily.data.length,1);
assert.equal(daily.data[0][1],22.5);
assert.throws(()=>H.csv('date,close\n'+Array.from({length:13},(_,i)=>`2026-02-${String(i+30).padStart(2,'0')},12`).join('\n')),/Tanggal CSV/);
const html=fs.readFileSync('index.html','utf8');
for(const p of ['assets/bazi-core.js','assets/bazi-ui.js','assets/market-trend-core.js','assets/market-trend-ui.js'])assert.ok(html.includes(p),p);
for(const p of ['technical-scanners-core.js','technical-scanners-ui.js','tabBBMA','tabLiquidity'])assert.ok(!html.includes(p));
const ui=fs.readFileSync('assets/bazi-ui.js','utf8');
assert.ok(!/[\u3400-\u9fff]/u.test(ui),'UI must show no Chinese glyphs');
const panel=fs.readFileSync('assets/market-trend-ui.js','utf8');
assert.ok(panel.includes('NAIK')&&panel.includes('World Bank'));
assert.ok(panel.includes('baziView')&&panel.includes('mhSymbol'));
console.log('PASS: monthly history validation, trend, gap guards, years, CSV, BaZi Indonesian UI and website wiring.');
