'use strict';
const A=require('node:assert/strict'),K=require('../assets/musang-pdf-core.js');
let total=0;function test(n,f){f();console.log('PASS',n);total++;}
const M=60000,T=Date.parse('2026-10-02T12:00:00Z');
const vals=[[110,111,109,110],[108,109,107,108],[106,107,105,106],[107,109,106,108],[110,112,109,111],[108,109,107,108],[104,105,100,103],[103,104,101,102],[102,106,102,105],[105,115,105,114],[113,114,103.2,104],[104,105,102.4,103.5]];
const b=vals.map(([open,high,low,close],i)=>({ms:T+i*M,open,high,low,close}));
const api=x=>({ok:true,symbol:'XAU/USD',timezone:'UTC',interval:'1min',values:x.map(c=>({datetime:new Date(c.ms).toISOString(),open:c.open,high:c.high,low:c.low,close:c.close}))});
const raw=K.detect(b,'M1').find(x=>x.direction==='BUY');
A.ok(raw,'BUY candidate detected');const s={...raw,verified:true,reviewedAt:T+10*M};const now=T+12*M+5000;
const good=K.evaluate(s,b,now),astro={model:true,groups:[{start:T,end:T+20*M,state:'BUY'}]};
const z={id:'one',tf:'H4',kind:'DEMAND',low:101,high:104,note:'synthetic test only',verified:true,active:true,createdAt:T};
test('candidate is unverified by default',()=>A.equal(raw.verified,false));
test('CB1 is between historical extremes',()=>{A.ok(raw.firstMs<raw.pullbackMs&&raw.pullbackMs<raw.newMs);A.equal(raw.cb1,112);});
test('Zone IB is broken candle body, not CB1',()=>{A.equal(raw.zoneMs,b[7].ms);A.equal(raw.low,102);A.equal(raw.high,103);});
test('Unreviewed candidate cannot signal',()=>A.equal(K.evaluate(raw,b,now).stage,'REVIEW_PDF'));
test('CB1 wick does not confirm',()=>{const q=b.slice(0,10).map(c=>({...c}));q[9].close=111;A.equal(K.evaluate(s,q,T+10*M).stage,'WAIT_CB1_BREAK');});
test('CB1 break alone not entry',()=>A.equal(K.evaluate(s,b.slice(0,10),T+10*M+1).stage,'WAIT_RETEST'));
test('Retest must follow break, not same candle',()=>{const q=b.slice(0,10).map(c=>({...c}));q[9].low=102.5;A.equal(K.evaluate(s,q,T+10*M).stage,'WAIT_RETEST');});
test('Reviewed fresh retest accepted',()=>{A.equal(good.stage,'RETEST_VALID');A.equal(good.entry,103);A.equal(good.eventMs,T+12*M);});
test('Expiry is half open',()=>A.equal(K.evaluate(s,b,T+13*M).stage,'HISTORICAL'));
test('Late manual verification cannot resurrect signal',()=>A.equal(K.evaluate({...s,reviewedAt:T+11*M+1},b,now).stage,'HISTORICAL'));
test('Exact-bar-open verification allowed',()=>A.equal(K.evaluate({...s,reviewedAt:T+11*M},b,now).stage,'RETEST_VALID'));
test('Target ratios exactly source 1.618 2.618 4.23',()=>A.deepEqual(good.targets.map(x=>x.ratio),[1.618,2.618,4.23]));
test('RR uses signed reward',()=>A.ok(good.targets.every(x=>x.rr>0)));
test('Missing SL blocks entry plan',()=>A.equal(K.evaluate({...s,sl:null},b,now).stage,'RISK_REVIEW'));
test('CB1 overlap invalid',()=>A.throws(()=>K.validate({...s,cb1:102.5})));
test('SL on wrong side invalid',()=>A.throws(()=>K.validate({...s,sl:105})));
test('Wrong Fibo orientation invalid',()=>A.throws(()=>K.validate({...s,fib100:100})));
test('Missing candle history fails closed',()=>A.equal(K.evaluate(s,b.filter((_,i)=>i!==10),now).stage,'MISSING_HISTORY'));
test('Retest and SL same candle is ambiguous',()=>{const q=b.map(c=>({...c}));q[11].low=100.9;A.equal(K.evaluate(s,q,now).stage,'AMBIGUOUS_BAR');});
test('Closed zone failure invalidates',()=>{const q=b.map(c=>({...c}));q[10].close=101;A.equal(K.evaluate(s,q,now).stage,'INVALID_ZONE');});
test('Newer candle makes prior event historical',()=>A.equal(K.evaluate(s,[...b,{...b[11],ms:T+12*M}],T+13*M+1).stage,'HISTORICAL'));
test('Forming candle excluded',()=>A.equal(K.candles(api(b),'M1',T+11*M+20000).length,11));
test('Malformed date rejected',()=>A.throws(()=>K.stamp('2026-02-31 12:00:00')));
test('Null OHLC rejected',()=>{const d=api(b);d.values[0].open=null;A.throws(()=>K.candles(d,'M1',now));});
test('OHLC ordering rejected',()=>{const d=api(b);d.values[0].low=999;A.throws(()=>K.candles(d,'M1',now));});
test('Duplicate timestamps rejected',()=>A.throws(()=>K.candles(api([...b,b[0]]),'M1',now)));
test('Wrong timezone rejected',()=>A.throws(()=>K.candles({...api(b),timezone:'Asia/Jakarta'},'M1',now)));
test('Wrong symbol rejected',()=>A.throws(()=>K.candles({...api(b),symbol:'EUR/USD'},'M1',now)));
test('Wrong interval rejected',()=>A.throws(()=>K.candles(api(b),'M5',now)));
test('BUY/SELL mirror symmetric',()=>{const q=b.map(c=>({ms:c.ms,open:220-c.open,high:220-c.low,low:220-c.high,close:220-c.close}));const c=K.detect(q,'M1').find(x=>x.direction==='SELL');A.ok(c);A.equal(K.evaluate({...c,verified:true,reviewedAt:T+10*M},q,now).stage,'RETEST_VALID');});
test('C1 works without HTF locations; C2 WAIT',()=>{const c=K.combine(good,astro,[],now,true);A.equal(c.one,'ENTRY BUY');A.equal(c.two,'WAIT');});
test('C2 accepts verified aligned location',()=>A.equal(K.combine(good,astro,[z],now,true).two,'ENTRY BUY'));
test('C2 rejects opposed location conflict',()=>A.equal(K.combine(good,astro,[z,{...z,id:'two',kind:'SUPPLY'}],now,true).two,'WAIT'));
test('All five context TFs supported',()=>K.CFG.context.forEach(tf=>A.equal(K.combine(good,astro,[{...z,tf}],now,true).two,'ENTRY BUY')));
test('Locations need not align all five TFs',()=>A.equal(K.combine(good,astro,[{...z,tf:'H1'}],now,true).two,'ENTRY BUY'));
test('Inactive zone excluded',()=>A.equal(K.combine(good,astro,[{...z,active:false}],now,true).two,'WAIT'));
test('Unverified zone excluded',()=>A.equal(K.combine(good,astro,[{...z,verified:false}],now,true).two,'WAIT'));
test('Newly added post-touch zone cannot retrofit confluence',()=>A.equal(K.combine(good,astro,[{...z,createdAt:T+11*M+1}],now,true).two,'WAIT'));
test('Astrology mismatch blocks C1 and C2',()=>{const c=K.combine(good,{model:true,groups:[{start:T,end:T+20*M,state:'SELL'}]},[z],now,true);A.equal(c.one,'WAIT');A.equal(c.two,'WAIT');});
test('Astrology past-date window blocks',()=>A.equal(K.combine(good,{model:true,groups:[{start:T-86400000,end:T-3600000,state:'BUY'}]},[z],now,true).one,'WAIT'));
test('Astrology changed after event blocks',()=>A.equal(K.combine(good,{model:true,groups:[{start:T,end:T+12*M+1,state:'BUY'},{start:T+12*M+1,end:T+20*M,state:'SELL'}]},[z],now,true).one,'WAIT'));
test('Astrology stale and OFF fail closed',()=>{A.equal(K.combine(good,astro,[z],now,true,true).one,'WAIT');A.equal(K.combine(good,{...astro,model:false},[z],now,true).one,'WAIT');});
test('Network stale clears both entry decisions',()=>{const c=K.combine(good,astro,[z],now,false);A.equal(c.one,'WAIT');A.equal(c.two,'WAIT');});
test('No order execution in all modes',()=>A.equal(K.combine(good,astro,[z],now,true).executionEnabled,false));
console.log('TOTAL_PASS',total);
module.exports={b,api,raw,s,good,astro,z,T,M,now};
