'use strict';
const assert=require('node:assert/strict'),N=require('../assets/snd-auto-core.js');
let count=0;function test(label,f){f();count++;console.log('PASS '+label);}
const H=3600000,D=24*H,T=Date.parse('2026-10-01T00:00:00Z');
const bar=(i,o,h,l,c)=>({ms:T+i*H,end:T+(i+1)*H,open:o,high:h,low:l,close:c,closed:true});
const seed={id:'x',tf:'H1',kind:'DEMAND',direction:'BUY',low:98,high:100,createdAt:T+3*H,originMs:T,departedAt:T+H,scale:2,note:'Auto test'};
test('WIB conversion',()=>assert.equal(N.wallUTC('2026-10-04 07:00:00','Asia/Jakarta'),Date.parse('2026-10-04T00:00:00Z')));
test('Reject bad dates',()=>assert.throws(()=>N.wallUTC('2026-02-30','UTC')));
test('Reject malformed hour',()=>assert.throws(()=>N.wallUTC('2026-10-04 25:00','UTC')));
test('Reject nonexistent DST hour',()=>assert.throws(()=>N.wallUTC('2026-03-08 02:30','America/New_York')));
test('Reject ambiguous DST hour',()=>assert.throws(()=>N.wallUTC('2026-11-01 01:30','America/New_York')));
test('Month rollover variable duration',()=>assert.equal(N.endOf('2026-02-01','MN1','UTC'),Date.parse('2026-03-01T00:00:00Z')));
test('Year rollover',()=>assert.equal(N.endOf('2026-12-01','MN1','UTC'),Date.parse('2027-01-01T00:00:00Z')));
test('Native daily zone DST',()=>assert.equal(N.endOf('2026-03-08','D1','America/New_York')-N.wallUTC('2026-03-08','America/New_York'),23*H));
test('FRESH after departure',()=>assert.equal(N.lifecycle(seed,[bar(1,104,106,103,105),bar(2,105,107,104,106)],'H1').status,'FRESH'));
test('First revisit counts immediately',()=>assert.equal(N.lifecycle(seed,[bar(1,102,104,99,103)],'H1').retests,1));
test('Contiguous touch counts one visit',()=>assert.equal(N.lifecycle(seed,[bar(1,102,104,99,103),bar(2,102,105,99,104)],'H1').retests,1));
test('Leave and revisit counts two visits',()=>assert.equal(N.lifecycle(seed,[bar(1,102,104,99,103),bar(2,104,108,103,105),bar(3,103,104,99,103)],'H1').retests,2));
test('Closed distal breach broken',()=>assert.equal(N.lifecycle(seed,[bar(1,100,101,96,97)],'H1').status,'BROKEN'));
test('Wick is tested, not closed break',()=>assert.equal(N.lifecycle(seed,[bar(1,101,102,97,101)],'H1').status,'TESTED'));
test('Forming bar cannot break source zone',()=>assert.equal(N.lifecycle(seed,[{...bar(1,100,101,96,97),closed:false}],'H1').status,'TESTED'));
test('Missing weekdays fail closed',()=>assert.equal(N.lifecycle(seed,[bar(1,104,106,103,105),bar(10,105,108,104,107)],'H1').status,'DATA_GAP'));
const fresh={...seed,status:'FRESH',low:80,high:81,createdAt:T,scale:2},tested={...seed,id:'test',status:'TESTED',low:99,high:100};
test('Fresh beats nearer tested',()=>assert.equal(N.ranked([tested,fresh],'BUY',100)[0].id,'x'));
test('Broken never ranked',()=>assert.equal(N.ranked([{...fresh,status:'BROKEN'}],'BUY',100).length,0));
test('Opposite bias excluded',()=>assert.equal(N.ranked([fresh],'SELL',100).length,0));
test('Nested across distinct TF',()=>{const r=N.ranked([fresh,{...fresh,id:'w',tf:'W1',low:79,high:82}],'BUY',100);assert.ok(r[0].nested.length===1);});
test('Same TF is not MTF confluence',()=>assert.equal(N.ranked([fresh,{...fresh,id:'copy'}],'BUY',100)[0].confluence.length,0));
const state={frames:{H1:{ok:true,validUntil:T+100*H,zones:[fresh]}}};
test('Partial TF usable not fabricate missing',()=>{const c=N.select(state,'BUY',80.5,T+H,T+2*H);assert.equal(c.aligned.length,1);assert.equal(c.missing.length,4);});
test('No retroactive location',()=>assert.equal(N.select(state,'BUY',80.5,T-H,T+2*H).aligned.length,0));
test('No stale location',()=>assert.equal(N.select(state,'BUY',80.5,T+H,T+101*H).aligned.length,0));
test('No outside-zone confluence',()=>assert.equal(N.select(state,'BUY',200,T+H,T+2*H).aligned.length,0));
const makePayload=()=>({ok:true,symbol:'XAU/USD',interval:'1h',timezone:'UTC',fetchedAtUtc:new Date(T+40*H).toISOString(),values:Array.from({length:40},(_,i)=>({datetime:new Date(T+i*H).toISOString().slice(0,19).replace('T',' '),open:100,high:102,low:99,close:101}))});
test('Valid native payload',()=>assert.equal(N.payload(makePayload(),'H1',T+40*H).closed.length,40));
test('Forming excluded from detector',()=>{const p=makePayload();p.fetchedAtUtc=new Date(T+39.5*H).toISOString();assert.equal(N.payload(p,'H1',T+39.5*H).closed.length,39);});
test('Duplicates rejected',()=>{const p=makePayload();p.values.push(p.values[0]);assert.throws(()=>N.payload(p,'H1',T+40*H));});
test('Null rejected not coerced to zero',()=>{const p=makePayload();p.values[0].low=null;assert.throws(()=>N.payload(p,'H1',T+40*H));});
test('Wrong instrument rejected',()=>{const p=makePayload();p.symbol='XAUUSDc';assert.throws(()=>N.payload(p,'H1',T+40*H));});
test('Wrong interval rejected',()=>assert.throws(()=>N.payload(makePayload(),'H4',T+40*H)));
test('Old fetch rejected',()=>assert.throws(()=>N.payload(makePayload(),'H1',T+41*H)));
const b=Array.from({length:40},(_,i)=>bar(i,105,106+(i%2)*.1,104,105));b[22]=bar(22,101,105,98,102);b[23]=bar(23,103,110,102,109);b[24]=bar(24,109,112,108,111);
for(let i=25;i<b.length;i++)b[i]=bar(i,110,113+(i%3)*.1,109,112);
const zs=N.scan({tf:'H1',closed:b,bars:b});
test('Automatic SNR and SND not manual',()=>{assert.ok(zs.some(z=>z.kind==='SUPPORT'));assert.ok(zs.some(z=>z.kind==='DEMAND'));});
test('Causal formation timestamp',()=>assert.ok(zs.filter(z=>z.originMs===b[22].ms).every(z=>z.createdAt>=b[24].end)));
test('Prefix invariance locked boundaries',()=>{const a=N.scan({tf:'H1',closed:b.slice(0,30),bars:b.slice(0,30)}).find(z=>z.originMs===b[22].ms);const c=zs.find(z=>z.id===a.id);assert.deepEqual([a.low,a.high,a.createdAt],[c.low,c.high,c.createdAt]);});
test('Supply mirror symmetric',()=>{const mirror=b.map(x=>({...x,open:220-x.open,high:220-x.low,low:220-x.high,close:220-x.close}));assert.ok(N.scan({tf:'H1',closed:mirror,bars:mirror}).some(z=>z.kind==='SUPPLY'));});
console.log('TOTAL_PASS',count);
