'use strict';
const fs=require('fs'),assert=require('assert');
const css=fs.readFileSync('assets/wallpaper.css','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(index.includes('assets/wallpaper.css?v=1.1.0'),'wallpaper cache version missing');
assert(css.includes('data:image/webp;base64,'),'embedded user wallpaper missing');
assert(css.includes('/* Glass completeness v1.1 */'),'glass v1.1 block missing');
assert(css.includes('.panel,.metric,details,.tech-card,.rule,.ts-card,.ts-controls,.adb-box,.an-box'),'dynamic glass surfaces missing');
assert(css.includes('td{\n  background:rgba(8,15,25,.22) !important;'),'transparent table body missing');
assert(css.includes('th{\n  background:rgba(8,15,25,.80) !important;'),'readable table header missing');
assert(css.includes('backdrop-filter:blur(4px)'),'glass blur missing');
assert(css.includes('.muted,.label,.head small,td small'),'muted text contrast override missing');
console.log('PASS wallpaper glass v1.1');
